/* ---------------------------------------------------------------------- */
/* Script generated with: DeZign for Databases 12.1.0                     */
/* Target DBMS:           PostgreSQL 12                                   */
/* Project file:          model.dez                                       */
/* Project name:                                                          */
/* Author:                                                                */
/* Script type:           Alter database script                           */
/* Created on:            2020-08-12 19:57                                */
/* ---------------------------------------------------------------------- */


/* ---------------------------------------------------------------------- */
/* Drop foreign key constraints                                           */
/* ---------------------------------------------------------------------- */

ALTER TABLE ENTORNOS.APLICACION_CLIENTE DROP CONSTRAINT FK_1_APLICACION_CLIENTE;

ALTER TABLE ENTORNOS.APLICACION_CLIENTE DROP CONSTRAINT FK_2_APLICACION_CLIENTE;

ALTER TABLE ENTORNOS.APLICACION_CLIENTE DROP CONSTRAINT FK_3_APLICACION_CLIENTE;

ALTER TABLE ENTORNOS.DEPENDENCIA_APLICACION DROP CONSTRAINT FK_1_DEPENDENCIA_APLICACION;

ALTER TABLE ENTORNOS.DEPENDENCIA_APLICACION DROP CONSTRAINT FK_2_DEPENDENCIA_APLICACION;

/* ---------------------------------------------------------------------- */
/* Drop and recreate table "ENTORNOS.APLICACION"                          */
/* ---------------------------------------------------------------------- */

ALTER TABLE ENTORNOS.APLICACION DROP CONSTRAINT PK_APLICACION;

CREATE TABLE ENTORNOS.APLICACION_TMP (
    ID_APLICACION identity  NOT NULL,
    APLICACION CHARACTER VARYING(40)  NOT NULL);

INSERT INTO ENTORNOS.APLICACION_TMP
    (APLICACION)
SELECT
    APLICACION
FROM ENTORNOS.APLICACION;


DROP TABLE ENTORNOS.APLICACION;

ALTER TABLE ENTORNOS.APLICACION_TMP RENAME TO APLICACION;

ALTER TABLE ENTORNOS.APLICACION ADD CONSTRAINT PK_APLICACION 
    PRIMARY KEY (ID_APLICACION);

/* ---------------------------------------------------------------------- */
/* Drop and recreate table "ENTORNOS.APLICACION_CLIENTE"                  */
/* ---------------------------------------------------------------------- */

ALTER TABLE ENTORNOS.APLICACION_CLIENTE DROP CONSTRAINT PK_APLICACION_CLIENTE;

CREATE TABLE ENTORNOS.APLICACION_CLIENTE_TMP (
    ID_APLICACION_CLIENTE identity  NOT NULL,
    ID_CLIENTE identity  NOT NULL,
    ID_SERVIDOR identity  NOT NULL,
    CONTENEDOR CHARACTER VARYING(40)  NOT NULL,
    ID_ENTORNO identity  NOT NULL,
    ID_APLICACION identity  NOT NULL,
    PUERTO SMALLINT);

INSERT INTO ENTORNOS.APLICACION_CLIENTE_TMP
    (ID_APLICACION_CLIENTE,ID_CLIENTE,ID_SERVIDOR,CONTENEDOR,ID_ENTORNO,PUERTO)
SELECT
    ID_APLICACION_CLIENTE,ID_CLIENTE,ID_SERVIDOR,CONTENEDOR,ID_ENTORNO,PUERTO
FROM ENTORNOS.APLICACION_CLIENTE;


DROP INDEX ENTORNOS.IDX_APLICACION_CLIENTE_1;

DROP TABLE ENTORNOS.APLICACION_CLIENTE;

ALTER TABLE ENTORNOS.APLICACION_CLIENTE_TMP RENAME TO APLICACION_CLIENTE;

ALTER TABLE ENTORNOS.APLICACION_CLIENTE ADD CONSTRAINT PK_APLICACION_CLIENTE 
    PRIMARY KEY (ID_APLICACION_CLIENTE);

CREATE UNIQUE INDEX IDX_APLICACION_CLIENTE_1 ON ENTORNOS.APLICACION_CLIENTE (ID_CLIENTE,ID_SERVIDOR,CONTENEDOR,ID_ENTORNO);

/* ---------------------------------------------------------------------- */
/* Add foreign key constraints                                            */
/* ---------------------------------------------------------------------- */

ALTER TABLE ENTORNOS.APLICACION_CLIENTE ADD CONSTRAINT FK_1_APLICACION_CLIENTE 
    FOREIGN KEY (ID_CLIENTE, ID_SERVIDOR, CONTENEDOR) REFERENCES eNTORNOS.CONTENEDOR (ID_CLIENTE,ID_SERVIDOR,CONTENEDOR);

ALTER TABLE ENTORNOS.APLICACION_CLIENTE ADD CONSTRAINT FK_2_APLICACION_CLIENTE 
    FOREIGN KEY (ID_APLICACION) REFERENCES ENTORNOS.APLICACION (ID_APLICACION);

ALTER TABLE ENTORNOS.APLICACION_CLIENTE ADD CONSTRAINT FK_3_APLICACION_CLIENTE 
    FOREIGN KEY (ID_CLIENTE, ID_ENTORNO) REFERENCES ENTORNOS.ENTORNO_CLIENTE (ID_CLIENTE,ID_ENTORNO);

ALTER TABLE ENTORNOS.DEPENDENCIA_APLICACION ADD CONSTRAINT FK_1_DEPENDENCIA_APLICACION 
    FOREIGN KEY (ID_APLICACION_CLIENTE) REFERENCES ENTORNOS.APLICACION_CLIENTE (ID_APLICACION_CLIENTE);

ALTER TABLE ENTORNOS.DEPENDENCIA_APLICACION ADD CONSTRAINT FK_2_DEPENDENCIA_APLICACION 
    FOREIGN KEY (ID_APLICACION_DEPENDE) REFERENCES ENTORNOS.APLICACION_CLIENTE (ID_APLICACION_CLIENTE);
