FROM node:12.18.3-alpine3.9

##########################################################################################

WORKDIR /apps

COPY package.json yarn.lock /apps/

RUN yarn install

ADD . /apps

CMD [ "yarn", "start" ]